---
- name: ensure copr repository for tvheadend is configured
  yum_repository:
    name: dani-tvheadend
    description: Copr repo for tvheadend owned by dani
    baseurl: https://copr-be.cloud.fedoraproject.org/results/dani/tvheadend/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/dani/tvheadend/pubkey.gpg
    gpgcheck: yes
    skip_if_unavailable: yes

- name: ensure packages are installed
  package:
    name: "{{ item }}"
  with_items:
    - python-netaddr
    - tvheadend

- name: ensure directory for recordings exists
  file:
    dest: "{{ tvheadend_recordings }}"
    state: directory
    recurse: yes
    owner: tvheadend
    group: tvheadend
    mode: "u=rwX,g=rX,o=rX"

- name: ensure acl is disabled
  lineinfile:
    dest: /etc/sysconfig/tvheadend
    regexp: '^OPTIONS=.*$'
    line: 'OPTIONS="-c /home/tvheadend/config -u tvheadend -g tvheadend -6 --http_port {{ tvheadend_port }} --htsp_port 9982 --noacl"'
  notify: restart tvheadend

- name: ensure service is running
  service:
    name: tvheadend
    enabled: yes
    state: running

- name: ensure nginx vhost is configured
  template:
    src: nginx_vhost.conf.j2
    dest: /etc/nginx/conf.d/vhost_tvheadend.conf
  notify: reload nginx
